/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdint.h>
#include <android/log.h>

/* Header for class com_wzh_yuvwater_jni_YuvOsdUtils */

#ifndef _Included_com_wzh_yuvwater_jni_YuvOsdUtils
#define _Included_com_wzh_yuvwater_jni_YuvOsdUtils

#define TAG    "YuvOsd" // 这个是自定义的LOG的标识
#define LOGD(...)  __android_log_print(ANDROID_LOG_DEBUG,TAG,__VA_ARGS__) // 定义LOGD类型


#ifdef __cplusplus
extern "C" {
#endif


/*
 * Class:     com_wzh_yuvwater_jni_YuvOsdUtils
 * Method:    run
 * Signature: ()V
 */

JNIEXPORT void JNICALL
Java_com_rokid_remote_record_YuvOsdUtils_initOsd(JNIEnv *env, jclass type, jint osdOffX,
                                                         jint osdOffY, jint patternLen, jint frameWidth,
                                                         jint frameHeight, jint rotation_angle, jint numWidth, jint numHeight);

JNIEXPORT void JNICALL
Java_com_rokid_remote_record_YuvOsdUtils_addOsd(
        JNIEnv *env, jclass type, jbyteArray yuv_in_data, jbyteArray yvu_out_data,
        jstring date_);

JNIEXPORT jcharArray JNICALL
Java_com_rokid_remote_record_YuvOsdUtils_argbIntToNV21Byte(JNIEnv *env, jclass jclazz, jintArray ints,
                                                                   jint width, jint height);

JNIEXPORT jcharArray JNICALL
Java_com_rokid_remote_record_YuvOsdUtils_argbIntToNV12Byte(JNIEnv *env, jclass jclazz, jintArray ints,
                                                                   jint width, jint height);

JNIEXPORT jcharArray JNICALL
Java_com_rokid_remote_record_YuvOsdUtils_argbIntToGrayNVByte(JNIEnv *env, jclass jclazz,
                                                                     jintArray ints,
                                                                     jint width, jint height);

JNIEXPORT void JNICALL
Java_com_rokid_remote_record_YuvOsdUtils_nv21ToNv12(JNIEnv *env, jclass type, jbyteArray nv21Src_,
                                                            jbyteArray nv12Dest_, jint width, jint height);



JNIEXPORT void JNICALL
Java_com_rokid_remote_record_YuvOsdUtils_releaseOsd(JNIEnv *env, jclass type);

JNIEXPORT void JNICALL
Java_com_rokid_remote_record_YuvOsdUtils_nv12ToRGB24(JNIEnv *env, jclass clazz, jbyteArray in,
                                                             jbyteArray out, jint width, jint height);

#ifdef __cplusplus
}
#endif
#endif
